name: Deploy to GitHub Pages

on:
  push:
    branches: "main"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Project with Environment Variables
        run: npx vite build --base=/Zajalzdndj/ || true
        env:
          # حقن مفاتيح ورابط Supabase الخاص بك في البناء السحابي
          VITE_SUPABASE_URL: "https://apykgrcuoetqzzojfnwf.supabase.co"
          VITE_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFweWtncmN1b2V0cXp6b2pmbndmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYxODMyNTAsImV4cCI6MjEwMTc1OTI1MH0.l7_xt7zuMvF8pJTgeBzT4MtRmVQFz0CaNiX8ePf2-q0"
          
          # حقن مفاتيح الأفلام والرفع والتليجرام المرفقة
          VITE_TMDB_API_KEY: "fea62da470cde92d5beb77af630a0854"
          VITE_IMGBB_API_KEY: "e9e89619f148fc6d25c412c38bd47977"
          VITE_TELEGRAM_BOT_TOKEN: "8828047234:AAGOy1wj7Q3ssFiMphKWn46lkUNlR7dblvE"
          VITE_TELEGRAM_CHAT_ID: "7855747323"

      - name: Check and Ensure Dist Folder
        run: mkdir -p dist && cp -r index.html dist/ || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
